apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-app
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/Rohit8329/devops-project
    path: helm-chart/myapp
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
